[package]
name = "nettest"
version = "0.1.0"
authors = ["KANDA Daisuke <dai1975@gmail.com>"]

[dependencies]
mio = "0.6.2"
mioco = "0.8.1"
futures = "0.1.7"
tokio-core = "0.1.2"
coio = { git = "https://github.com/zonyitoo/coio-rs.git" }

